/*****************************************************************************
* ROLLOPOD 1.69" LCD (ST7789V2 240x280) - Multi-GIF Playlist Player
* Automatically loops through multiple animations with seamless transitions!
******************************************************************************/

#include <Arduino.h>
#include <SPI.h>
#include "LCD_Driver.h"
#include "DEV_Config.h"
#include "frames_data.h" // Automatically generated by `generate_gif_code.py`

// Max display width buffer (280 in landscape, 240 in portrait)
#define MAX_DISP_WIDTH 280
uint16_t scaledLine[MAX_DISP_WIDTH];

int currentAnimIndex = 0;
const int LOOPS_PER_ANIMATION = 4; // Number of times to loop each GIF before switching

// Universal Full-Screen Frame Renderer
void DrawFrame(const uint8_t *frameData) {
    const int dispW = IS_LANDSCAPE ? 280 : 240;
    const int dispH = IS_LANDSCAPE ? 240 : 280;

    LCD_SetCursor(0, 0, dispW - 1, dispH - 1);
    
    DEV_Digital_Write(DEV_DC_PIN, 1);
    DEV_Digital_Write(DEV_CS_PIN, 0);

    const size_t lineBytes = FRAME_WIDTH * 2;

#if SCALE_FACTOR == 1
    // Native 1X Full High-Definition Direct SPI Stream
    for (int y = 0; y < FRAME_HEIGHT; y++) {
        SPI.writeBytes((uint8_t *)(frameData + y * lineBytes), lineBytes);
    }

#elif SCALE_FACTOR == 2
    // 2X Hardware Scaler (120x140 -> 240x280 or 140x120 -> 280x240)
    for (int y = 0; y < FRAME_HEIGHT; y++) {
        const uint16_t *srcLine = (const uint16_t *)(frameData + y * lineBytes);
        for (int x = 0; x < FRAME_WIDTH; x++) {
            uint16_t pixel = srcLine[x];
            scaledLine[2 * x]     = pixel;
            scaledLine[2 * x + 1] = pixel;
        }
        // Stream each line twice vertically
        SPI.writeBytes((uint8_t *)scaledLine, dispW * 2);
        SPI.writeBytes((uint8_t *)scaledLine, dispW * 2);
    }

#elif SCALE_FACTOR == 3
    // 3X Hardware Scaler (80x93 -> 240x280 or 93x80 -> 280x240)
    for (int y = 0; y < FRAME_HEIGHT; y++) {
        const uint16_t *srcLine = (const uint16_t *)(frameData + y * lineBytes);
        for (int x = 0; x < FRAME_WIDTH; x++) {
            uint16_t pixel = srcLine[x];
            scaledLine[3 * x]     = pixel;
            scaledLine[3 * x + 1] = pixel;
            scaledLine[3 * x + 2] = pixel;
        }
        // Stream each line 3 times vertically
        SPI.writeBytes((uint8_t *)scaledLine, dispW * 2);
        SPI.writeBytes((uint8_t *)scaledLine, dispW * 2);
        SPI.writeBytes((uint8_t *)scaledLine, dispW * 2);
    }
#endif

    DEV_Digital_Write(DEV_CS_PIN, 1);
}

void setup()
{
    // Initialize Hardware SPI & GPIO for ESP32
    Config_Init();
    
    // Initialize ST7789V2 LCD with selected orientation
    LCD_Init(IS_LANDSCAPE);

    // Turn backlight to maximum brightness
    LCD_SetBacklight(100);

    // Clear screen to black
    LCD_Clear(0x0000);
}

void loop()
{
    // Get current animation from playlist
    const Animation &currentAnim = animation_playlist[currentAnimIndex];

    // Loop current animation for a few cycles
    for (int loopCount = 0; loopCount < LOOPS_PER_ANIMATION; loopCount++) {
        for (int i = 0; i < currentAnim.numFrames; i++) {
            // Check for Serial command to switch animation manually ('N' = Next)
            if (Serial.available()) {
                char c = Serial.read();
                if (c == 'N' || c == 'n') {
                    currentAnimIndex = (currentAnimIndex + 1) % TOTAL_ANIMATIONS;
                    return;
                }
            }

            DrawFrame(currentAnim.frames[i]);
            delay(currentAnim.delayMs);
        }
    }

    // Automatically transition to the next animation in the playlist
    currentAnimIndex = (currentAnimIndex + 1) % TOTAL_ANIMATIONS;
}
